# Generated by Django 4.1 on 2024-03-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名：')),
                ('age', models.IntegerField(default=0, verbose_name='年齢：')),
                ('address', models.CharField(max_length=255, verbose_name='住所：')),
                ('hobby', models.CharField(max_length=255, verbose_name='趣味：')),
                ('job', models.CharField(max_length=100, verbose_name='業種：')),
                ('job_history', models.CharField(max_length=255, verbose_name='職歴：')),
                ('skill', models.CharField(max_length=255, verbose_name='資格：')),
                ('post', models.CharField(max_length=100, verbose_name='役職：')),
                ('mail', models.EmailField(max_length=254, verbose_name='メールアドレス：')),
                ('phone_num', models.CharField(max_length=20, verbose_name='電話番号：')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('memo', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
        migrations.CreateModel(
            name='CustInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_name', models.CharField(max_length=100, verbose_name='氏名：')),
                ('Company', models.CharField(max_length=255, verbose_name='会社名：')),
                ('Cust_mail', models.EmailField(max_length=254, verbose_name='メールアドレス：')),
                ('Company_address', models.CharField(max_length=255, verbose_name='会社住所：')),
                ('Cust_post', models.CharField(max_length=100, verbose_name='役職：')),
                ('Cust_job', models.CharField(max_length=100, verbose_name='業種：')),
                ('Cust_skill', models.CharField(max_length=255, verbose_name='資格：')),
                ('Cust_phone_num', models.CharField(max_length=20, verbose_name='電話番号：')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('importance_level', models.IntegerField(default=0, verbose_name='重要度：')),
                ('memo', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custmanage.userinfo')),
            ],
            options={
                'db_table': 'Cust_info',
            },
        ),
    ]
