# Generated by Django 4.1 on 2024-03-19 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('Company', models.CharField(max_length=255, verbose_name='会社名')),
                ('Cust_mail', models.EmailField(default='', max_length=254, verbose_name='メールアドレス')),
                ('Company_address', models.CharField(default='', max_length=255, verbose_name='会社住所')),
                ('Cust_post', models.CharField(default='', max_length=100, verbose_name='役職')),
                ('Cust_job', models.CharField(default='', max_length=100, verbose_name='業種')),
                ('Cust_skill', models.CharField(default='', max_length=255, verbose_name='資格')),
                ('Cust_phone_num', models.CharField(default='', max_length=20, verbose_name='電話番号')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('importance_level', models.IntegerField(default=0, verbose_name='重要度')),
                ('memo', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cust_info',
            },
        ),
    ]
