# Generated by Django 4.1 on 2024-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinfo',
            name='Cust_job',
            field=models.CharField(max_length=100, verbose_name='業種'),
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='Cust_skill',
            field=models.CharField(max_length=255, verbose_name='資格'),
        ),
    ]
